### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Bzhdad** [nintendaii/UnityNotifPlugin#12]
I am quite new to programming. and I do not quite understand how you can use your work. I would really like to create a background service in unity, but I don't know how to transfer data from Github to the program. whether the part needs to be created in android studio. please, help

**Comment by Bzhdad** [comment]
Я побачив у вас скріншоти українською, може рідною мовою буде зрозуміліше)

**Comment by nintendaii** [comment]
Hello. In order to download the project you need to clone it to your machine. You can use GitHub Desktop or simply download ZIP (see screenshot). You will have two folders - one is Android project (you need Android studio to open it), and the second one is the Unity project (you need an Unity version installed to your machine). All the code related to the functionality of the plugin is inside the Android project, and the actual app that uses this plugin is in Unity project.
<img width="408" alt="Screenshot 2022-12-27 at 15 43 48" src="https://user-images.githubusercontent.com/44233090/209675358-4d697425-90d7-4898-a448-85de24104f39.png">

**Comment by nintendaii** [comment]
> 

Дякую) Але на GitHub бажано писати англійською, оскільки так всі користувачі бачитимуть вашу проблему і зможуть з легкістю зрозуміти в чому проблема. Якщо ж у вас виникли питання, які складно написати англійською, то пишіть мені на email, я з легкістю відповім вам на українській) Слава Україні!

**Comment by Bzhdad** [comment]
Героям Слава! Дякую за підказки! Останнє питання залишилось. Мені потрібно
щоб у 00:00 функція додавала до List<string> currentsteps. Як це можливо
додати, це буде зробити зручніше в Unity або Android Studio та в яку
функцію мені потрібно додати строки If(dateTime.Now...) і так далі..



вт, 27 дек. 2022 г. в 16:53, Daniel ***@***.***>:

**Comment by Bzhdad** [comment]
Sorry, i think i write on your mail.

I need to create app that save current steps on 00:00 everyday on some kind of List<> and do it foreground

**Comment by nintendaii** [comment]
I think the best way to write the logic related to steps counting is to write it inside Unity since the Android plugin simply provides you the steps in time range that you can specify by yourself.

**Comment by Bzhdad** [comment]
Thanks for the tip!

вс, 1 янв. 2023 г., 20:27 Daniel ***@***.***>:

**Comment by nintendaii** [comment]
You have the Start Service function. From this moment, your plugin starts and starts counting steps. You can run the plugin whenever it's convenient for you.
![image](https://user-images.githubusercontent.com/44233090/210270541-539358a2-3d1f-4373-b341-79ae24446a2b.png)
The GetCurrentSteps function allows you to get the CURRENT number of steps since the service started.
That is, for example, you started the service (called the StartService method) at 12:00. Your plugin has started (counting steps). Then you decide to call the GetCurrentSteps method at 6:00 p.m. This means that the method will return you the number of steps from 12 to 18
![image](https://user-images.githubusercontent.com/44233090/210270582-e8ac42aa-a89f-446e-bce4-85262ab97815.png)
Using these two methods, you can receive and store the number of steps in any form and do whatever you want with this data. Note that after you call the GetCurrentSteps method, the steps are NOT counted.
I hope this helped you. If you have any other questions, write me.
