### ISSUE TITLE
"Permision isnt granted" when using in a different project

### ISSUE THREAD

**Issue by kojacksae** [nintendaii/UnityNotifPlugin#2]
Building your unity project and running on my Note 8 works great. But when I place the same plugin (in Assets/Plugins/Android) and same BackgroundService.cs script in another project (same project settings, same unity version: 2020.2.5f1) steps are always 0 and logcat shows "PEDOMETER: Permision isnt granted!"

Is there something I need to do to allow the plugin to work in another project?

**Comment by nintendaii** [comment]
Hi, in this project I use Unity version 2020.1.17f. However, I am not sure the problem is in the Unity side. There is might be some permission issues in the Android side. "PEDOMETER: Permision isnt granted!" error occurs if the popup (see the attached screenshot) with activity recognition does not appear. Does this popup appear in your case?
![photo_2021-03-18_23-15-33](https://user-images.githubusercontent.com/44233090/111698969-2b429380-8840-11eb-9812-904f296bedc3.jpg)
